[versions]
agp = "8.13.1"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
logger = "2.2.0"
material = "1.13.0"
constraintlayout = "2.2.1"
navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"
apKubaSdk = "1.0.0"
okhttp = "5.3.0"
okhttpTls = "5.3.0"
gson = "2.13.2"
codeScanner = "2.3.2"
core = "3.5.3"
apklislicensevalidator = "v.1.0.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logger = { module = "com.orhanobut:logger", version.ref = "logger" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-tls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttpTls" }
code-scanner = { module = "com.github.yuriy-budiyev:code-scanner", version.ref = "codeScanner" }
core = { module = "com.google.zxing:core", version.ref = "core" }
javase = { module = "com.google.zxing:javase", version.ref = "core" }
apklislicensevalidator = { module = "com.github.z17-cuba:ApklisLicenseValidator", version.ref = "apklislicensevalidator" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "maven-publish" }

